name = "parcode"
version = "0.5.3"
description = "Blazing fast parallel caching for Rust. Serializes complex data to a chunked file format to get CPU maximum power on data loads, but as a simple binary loader."

[scripts.test]
run = [
    "# === Running all standard quality tests... ===",
    "@> cargo fmt -- --check",
    "@> cargo clippy --all-features --all-targets -- -D warnings",
    "@> cargo test --all-features --all-targets",
    "# <#green>=== Completed! now you can make a PR. ===<#reset>",
]
desc = "Run a standard quality test required from make a PR."

[options.at_start]
desc = "Commands to run when entering a session (e.g., `source .venv/bin/activate`)"
run = "# echo 'Entering session...'"

[options.at_exit]
desc = "Commands to run when exiting a session (e.g., `docker-compose down`)"
run = "# echo 'Exiting session...'"

[options.open_with]

[vars]
GREETING = "Hello from an axes variable!"

[env]
